# SOPS configuration for secrets/ directory
# Auto-applied to all files matching path_regex in this directory.
#
# Setup: Run 'gmake secrets-setup' to generate your age key and populate
# this file with your public key.
#
# After setup, encrypt a file with:
#   SOPS_AGE_KEY_FILE=~/.config/sops/age/keys.txt sops secrets/myfile.sops.env
#
# Or via Make:
#   gmake secrets-edit FILE=secrets/myfile.sops.env

creation_rules:
  - path_regex: .*\.sops\..*
    age: >-
      # REPLACE_WITH_YOUR_AGE_PUBLIC_KEY
      # Run: gmake secrets-setup
